version: '2'

services:
  web:
    restart: always
    build: .
    environment:
      # https://docs.python.org/3/using/cmdline.html#cmdoption-u
      - PYTHONUNBUFFERED=true
      # Configure Flask app
      - FLASK_CONFIG=config.DevelopmentConfig
      # Pass environment variables from .env in containers
      # https://docs.docker.com/compose/environment-variables/
      - LMS_TOKEN
    ports:
      - "8000:8000"
    command: >
      gunicorn
        run:app
        --bind 0.0.0.0:8000
        --access-logfile -

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
