version: '2'

services:
  web:
    restart: always
    build: .
    environment:
      # https://docs.python.org/3/using/cmdline.html#cmdoption-u
      - PYTHONUNBUFFERED=true
      # Configure Flask app
      - FLASK_CONFIG=config.DevelopmentConfig
      # Pass environment variables from .env in containers
      # https://docs.docker.com/compose/environment-variables/
      - LMS_TOKEN
    ports:
      # HOST:CONTAINER
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    # Serve with Gunicorn
    # NOTE: Gunicorn logs to stderr by default since 19.2, so no need for "--log-file -" or "--error-logfile -"
    command: >
      gunicorn
        run:app
        --bind 0.0.0.0:8000
        --access-logfile -
        --reload

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
